---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "external-dns-management.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ include "external-dns-management.chart" . }}
    app.kubernetes.io/name: {{ include "external-dns-management.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- if .Values.serviceAccountAnnotations }}
  annotations:
{{ toYaml .Values.serviceAccountAnnotations | indent 4 }}
{{- end }}
